CFLAGS=-I./inc -g -Wall -Werror
GXX = g++

part1:
	@$(GXX) part1.cpp
	@./a.out input.ppm output_part1.ppm

part2_1a:
	@$(GXX) part2_1a.cpp
	@./a.out input.ppm output_part2_1a.ppm
	
part2_1b:
	@$(GXX) part2_1b.cpp
	@./a.out input.ppm output_part2_1b.ppm
	
part2_2:
	@$(GXX) part2_2.cpp
	@./a.out input.ppm output_part2_2.ppm
	
part2_3:
	@$(GXX) part2_3.cpp
	@./a.out input.ppm output_part2_3.ppm

clean: 
	@ rm a.out output_part1.ppm output_part2_1a.ppm output_part2_1b.ppm output_part2_2.ppm output_part2_3.ppm

