fifo: FIFO.cpp
	@g++ -std=c++11 -o fifo FIFO.cpp -lstdc++
	@./fifo 60 20 60 req1.dat 
lru: LRU.cpp
	@g++ -std=c++11 -o lru LRU.cpp -lstdc++
	@./fifo 60 20 60 req1.dat
random: Random.cpp
	@g++ -std=c++11 -o random Random.cpp -lstdc++
	@./fifo 60 20 60 req1.dat