part1:
	@g++ part1.cpp
	@time -p ./a.out input.ppm output_part1.ppm

part2_1a:
	@g++ part2_1a.cpp
	@time -p ./a.out input.ppm output_part2_1a.ppm
	
part2_1b:
	@g++ part2_1b.cpp
	@time -p ./a.out input.ppm output_part2_1b.ppm
	
part2_2:
	@g++ part2_2.cpp
	@time -p ./a.out input.ppm output_part2_2.ppm
	
part2_3:
	@g++ part2_3.cpp
	@time -p ./a.out input.ppm output_part2_3.ppm

clean: 
	@ rm a.out output_part1.ppm output_part2_1a.ppm output_part2_1b.ppm output_part2_2.ppm output_part2_3.ppm

